### ISSUE TITLE
Asynchronous chunk load

### ISSUE THREAD

**Issue by Betterovsky** [Imanity-Software/ImanitySpigot3-git#123]
### Is your feature request related to a problem?

[15:35:23] [WARN]: java.lang.IllegalStateException: Asynchronous chunk load!
[15:35:23] [WARN]: 	at org.spigotmc.AsyncCatcher.catchOp(SourceFile:14)
[15:35:23] [WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.loadChunk(SourceFile:370)
[15:35:23] [WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftChunk.load(SourceFile:137)
[15:35:23] [WARN]: 	at (hide)
[15:35:23] [WARN]: 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[15:35:23] [WARN]: 	at (hide)
[15:35:23] [WARN]: 	at (hide)
[15:35:23] [WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(SourceFile:59)
[15:35:23] [WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(SourceFile:53)
[15:35:23] [WARN]: 	at org.github.paperspigot.ServerSchedulerReportingWrapper.run(SourceFile:22)
[15:35:23] [WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[15:35:23] [WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[15:35:23] [WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)

### Describe the solution you'd like.

Adding the ability to load for the player asynchronously. chunks.load() with Imanity asyncChunkLoads enabled.

### Describe alternatives you've considered.

I want to get the effect of loading chunks for the player before teleportation.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest ImanitySpigot3.

**Comment by LeeGodSRC** [comment]
We do support async chunk load but the function it self isn't thread-safe.
you still have to call chunk load in main-thread.

I'd suggest you to use our get chunk async API to achieve what you wish:
https://docs.imanity.dev/books/imanityspigot-3/page/extended-api-methods#bkmrk-world

```java
World.imanity().getChunkAtAsynchronously(x, z, AsyncPriority.NORMAL).thenRun(() -> {
    // Callback after chunk load
});
```
