### ISSUE TITLE
Unable to generate timings report

### ISSUE THREAD

**Issue by HappyAreaBean** [Imanity-Software/ImanitySpigot3-git#128]
### Stack trace

```java
[12:44:43 ERROR]: Could not paste timings
java.net.UnknownHostException: ef0a459e-e070-4f10-9366-dcac040275f3: ef0a459e-e070-4f10-9366-dcac040275f3: Temporary failure in name resolution
        at java.net.InetAddress.getLocalHost(InetAddress.java:1506) ~[?:1.8.0_332]
        at co.aikar.timings.TimingsExport.run(TimingsExport.java:316) ~[spigot.jar:git-iSpigot-PaperEdition]
Caused by: java.net.UnknownHostException: ef0a459e-e070-4f10-9366-dcac040275f3: Temporary failure in name resolution
        at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929) ~[?:1.8.0_332]
        at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324) ~[?:1.8.0_332]
        at java.net.InetAddress.getLocalHost(InetAddress.java:1501) ~[?:1.8.0_332]
        ... 1 more
```

### Plugin list

N/A

### Steps/models to reproduce (if known)

1. Start and join the server
2. /timings report

### ImanitySpigot3 version

2022.05.3 BUILD 3

### Agreements

- [X] I am running the latest version of ImanitySpigot3 available from
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have compared the issue inbetween TacoSpigot 1.8.8 and ImanitySpigot3 And only ImanitySpigot3 occured this issue.

**Comment by LeeGodSRC** [comment]
This is probably a problem in your host can't connect to https://timin.gs/
You can try turning `timinGsSupport` in imanity/config.yml off to use the old site for timing service

**Comment by HappyAreaBean** [comment]
> This is probably a problem in your host can't connect to https://timin.gs/ You can try turning `timinGsSupport` in imanity/config.yml off to use the old site for timing service

I changed `timinGsSupport` to false and nothing changed.
