### ISSUE TITLE
SlimeWorldManager incompatible with parallelEntityTracking

### ISSUE THREAD

**Issue by lcx06** [Imanity-Software/ImanitySpigot3-git#13]
### Expected behavior

The SWM worlds loaded as expected

### Observed/Actual behavior

An error while loading it:

[15:23:46 WARN]: [henticator #1] java.lang.ClassCastException: com.grinderwolf.swm.nms.v1_8_R3.CustomChunkLoader cannot be cast to net.minecraft.server.v1_8_R3.ChunkRegionLoader
[15:23:46 WARN]: [henticator #1]        at org.imanity.imanityspigot.bK.<init>(SourceFile:33)
[15:23:46 WARN]: [henticator #1]        at net.minecraft.server.v1_8_R3.ImanityAsyncChunkProvider.<init>(SourceFile:65)
[15:23:46 WARN]: [henticator #1]        at net.minecraft.server.v1_8_R3.WorldServer.k(SourceFile:900)
[15:23:46 WARN]: [henticator #1]        at net.minecraft.server.v1_8_R3.WorldServer.<init>(SourceFile:83)
[15:23:46 WARN]: [henticator #1]        at com.grinderwolf.swm.nms.v1_8_R3.CustomWorldServer.<init>(CustomWorldServer.java:34)
[15:23:46 WARN]: [henticator #1]        at com.grinderwolf.swm.nms.v1_8_R3.v1_8_R3SlimeNMS.createNMSWorld(v1_8_R3SlimeNMS.java:84)
[15:23:46 WARN]: [henticator #1]        at com.grinderwolf.swm.nms.v1_8_R3.v1_8_R3SlimeNMS.generateWorld(v1_8_R3SlimeNMS.java:89)
[15:23:46 WARN]: [henticator #1]        at com.grinderwolf.swm.plugin.SWMPlugin.generateWorld(SWMPlugin.java:343)
[15:23:46 WARN]: [henticator #1]        at dev.lcx06.skyblockms.data.Island.loadWorld(Island.java:145)
[15:23:46 WARN]: [henticator #1]        at dev.lcx06.skyblockms.data.QueryManager.loadIsland(QueryManager.java:71)
[15:23:46 WARN]: [henticator #1]        at dev.lcx06.skyblockms.data.QueryManager.loadGameUser(QueryManager.java:38)
[15:23:46 WARN]: [henticator #1]        at dev.lcx06.skyblockms.data.GameUser.<init>(GameUser.java:47)
[15:23:46 WARN]: [henticator #1]        at dev.lcx06.skyblockms.data.GameUserManager.load(GameUserManager.java:13)
[15:23:46 WARN]: [henticator #1]        at dev.lucianxd16.servercore.listener.PreLogin.onPrelogin(PreLogin.java:59)
[15:23:46 WARN]: [henticator #1]        at spg.lgdev.events.executor.asm.generated.GeneratedEventExecutor104.execute(Unknown Source)
[15:23:46 WARN]: [henticator #1]        at org.imanity.imanityspigot.executor.EventExecutorGenerator.lambda$create$1(EventExecutorGenerator.java:60)
[15:23:46 WARN]: [henticator #1]        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74)
[15:23:46 WARN]: [henticator #1]        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[15:23:46 WARN]: [henticator #1]        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:537)
[15:23:46 WARN]: [henticator #1]        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:523)
[15:23:46 WARN]: [henticator #1]        at net.minecraft.server.v1_8_R3.LoginListener$LoginHandler.fireEvents(SourceFile:262)
[15:23:46 WARN]: [henticator #1]        at net.minecraft.server.v1_8_R3.LoginListener.lambda$a$2(SourceFile:223)
[15:23:46 WARN]: [henticator #1]        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[15:23:46 WARN]: [henticator #1]        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[15:23:46 WARN]: [henticator #1]        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[15:23:46 WARN]: [henticator #1]        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[15:23:46 WARN]: [henticator #1]        at java.lang.Thread.run(Thread.java:748)

### Steps/models to reproduce

Load a saved world with the SWM API or with /swm load

### Plugin list

FastAsyncWorldEdit, ViaVersion, SlimeWorldManager, ProtocolLib, LuckPerms, WorldEdit, Vault, Citizens, ServerCore

### ImanitySpigot3 version

2021.08.1 BUILD 1

### Agreements

- [X] I am running the latest version of ImanitySpigot3 available from
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have compared the issue inbetween TacoSpigot 1.8.8 and ImanitySpigot3 And only ImanitySpigot3 occured this issue.

**Comment by HappyAreaBean** [comment]
Hello lcx06,

SlimeWorldManager is comptibale with ImanitySpigot 3. In case you want to do that you will need to change some setting in the config.yml.
Please follow this instruction for more info: [Q: SlimeWorldManager have error when starting](https://docs.imanity.dev/books/frequently-asked-question/page/imanityspigot-3)

Have a great day!

**Comment by lcx06** [comment]
Okey, now it loads the world correctly, but there is two more errors after it's loaded, I need to change any other option?

> [15:50:31] [ERROR]: [Server thread] "Silently" catching entity tracking error.
net.minecraft.server.v1_8_R3.ReportedException: Adding entity to track
	at net.minecraft.server.v1_8_R3.EntityTracker.addEntity(SourceFile:178) ~[spigot.jar:git-iSpigot-PaperEdition]
	at net.minecraft.server.v1_8_R3.EntityTracker.addEntity(SourceFile:130) ~[spigot.jar:git-iSpigot-PaperEdition]
	at net.minecraft.server.v1_8_R3.EntityTracker.track(SourceFile:60) ~[spigot.jar:git-iSpigot-PaperEdition]
	at net.minecraft.server.v1_8_R3.WorldManager.a(SourceFile:18) ~[spigot.jar:git-iSpigot-PaperEdition]
	at net.minecraft.server.v1_8_R3.World.a(SourceFile:1299) ~[spigot.jar:git-iSpigot-PaperEdition]
	at net.minecraft.server.v1_8_R3.WorldServer.a(SourceFile:1128) ~[spigot.jar:git-iSpigot-PaperEdition]
	at net.minecraft.server.v1_8_R3.World.addEntity(SourceFile:1290) ~[spigot.jar:git-iSpigot-PaperEdition]
	at net.minecraft.server.v1_8_R3.World.addEntity(SourceFile:1211) ~[spigot.jar:git-iSpigot-PaperEdition]
	at net.minecraft.server.v1_8_R3.PlayerList.onPlayerJoin0(SourceFile:422) ~[spigot.jar:git-iSpigot-PaperEdition]
	at net.minecraft.server.v1_8_R3.PlayerList.a0(SourceFile:195) ~[spigot.jar:git-iSpigot-PaperEdition]
	at net.minecraft.server.v1_8_R3.PlayerList.lambda$a$0(SourceFile:108) ~[spigot.jar:git-iSpigot-PaperEdition]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) ~[?:1.8.0_282]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646) ~[?:1.8.0_282]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) ~[?:1.8.0_282]
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975) ~[?:1.8.0_282]
	at net.minecraft.server.v1_8_R3.WorldNBTStorage.lambda$null$4(SourceFile:311) ~[spigot.jar:git-iSpigot-PaperEdition]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_282]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_282]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:18) ~[spigot.jar:git-iSpigot-PaperEdition]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(SourceFile:904) ~[spigot.jar:git-iSpigot-PaperEdition]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(SourceFile:447) ~[spigot.jar:git-iSpigot-PaperEdition]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(SourceFile:835) ~[spigot.jar:git-iSpigot-PaperEdition]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(SourceFile:737) ~[spigot.jar:git-iSpigot-PaperEdition]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
Caused by: java.lang.UnsupportedOperationException
	at net.minecraft.server.v1_8_R3.EntityTrackerEntry.scanPlayers(SourceFile:629) ~[spigot.jar:git-iSpigot-PaperEdition]
	at net.minecraft.server.v1_8_R3.EntityTracker.onEntityTracked(SourceFile:46) ~[spigot.jar:git-iSpigot-PaperEdition]
	at net.minecraft.server.v1_8_R3.EntityTracker.addEntity(SourceFile:150) ~[spigot.jar:git-iSpigot-PaperEdition]
	... 23 more

> [15:50:50 FATAL]: [Server thread] Error executing task
java.util.concurrent.ExecutionException: net.minecraft.server.v1_8_R3.ReportedException: Ticking player
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_282]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_282]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:19) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(SourceFile:904) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(SourceFile:447) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(SourceFile:835) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(SourceFile:737) ~[spigot.jar:git-iSpigot-PaperEdition]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
Caused by: net.minecraft.server.v1_8_R3.ReportedException: Ticking player
        at net.minecraft.server.v1_8_R3.EntityPlayer.l(SourceFile:378) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(SourceFile:399) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.PacketPlayInFlying.a(SourceFile:23) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.PacketPlayInFlying.a(SourceFile:8) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(PlayerConnectionUtils.java:16) ~[spigot.jar:git-iSpigot-PaperEdition]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_282]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_282]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:18) ~[spigot.jar:git-iSpigot-PaperEdition]
        ... 5 more
Caused by: java.lang.UnsupportedOperationException
        at net.minecraft.server.v1_8_R3.EntityTrackerEntry.scanPlayers(SourceFile:629) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.EntityTracker.a(SourceFile:243) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.EntityPlayer.B(SourceFile:1160) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.EntityLiving.bi(SourceFile:518) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.EntityLiving.K(SourceFile:264) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.Entity.t_(SourceFile:277) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.EntityLiving.t_(SourceFile:1532) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.EntityHuman.t_(SourceFile:204) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.EntityPlayer.l(SourceFile:313) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(SourceFile:399) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.PacketPlayInFlying.a(SourceFile:23) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.PacketPlayInFlying.a(SourceFile:8) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(PlayerConnectionUtils.java:16) ~[spigot.jar:git-iSpigot-PaperEdition]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_282]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_282]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:18) ~[spigot.jar:git-iSpigot-PaperEdition]
        ... 5 more

**Comment by HappyAreaBean** [comment]
Thank you for the report! Our team will investigate this problem.
At the mean time you can temporarily fixing this problem by disable `parallelEntityTracking` in config.yml

#### **NOTE: This is only a temporary fix, you should consider to change back the settings when the problem officially get fixed.**

**Comment by LeeGodSRC** [comment]
The problem has been solved in **2021.08.1 BUILD 2**
