### ISSUE TITLE
Netty Patch doesn't work while running Java 16 with ImanitySpigot3

### ISSUE THREAD

**Issue by AndreiD2015** [Imanity-Software/ImanitySpigot3-git#14]
### Stack trace

```
[18:52:24] [ERROR]: [Rancha Thread] Could not patch Netty! Try contacting Imanity Developers!
java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @4434095f
	at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357) ~[?:?]
	at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297) ~[?:?]
	at java.lang.reflect.Method.checkCanSetAccessible(Method.java:199) ~[?:?]
	at java.lang.reflect.Method.setAccessible(Method.java:193) ~[?:?]
	at org.bukkit.craftbukkit.libs.javassist.util.proxy.SecurityActions.setAccessible(SecurityActions.java:159) ~[javaassist-3.28.0-GA-remapped.jar:?]
	at org.bukkit.craftbukkit.libs.javassist.util.proxy.DefineClassHelper$JavaOther.defineClass(DefineClassHelper.java:213) ~[javaassist-3.28.0-GA-remapped.jar:?]
	at org.bukkit.craftbukkit.libs.javassist.util.proxy.DefineClassHelper$Java11.defineClass(DefineClassHelper.java:52) ~[javaassist-3.28.0-GA-remapped.jar:?]
	at org.bukkit.craftbukkit.libs.javassist.util.proxy.DefineClassHelper.toClass(DefineClassHelper.java:260) ~[javaassist-3.28.0-GA-remapped.jar:?]
	at org.bukkit.craftbukkit.libs.javassist.ClassPool.toClass(ClassPool.java:1240) ~[javaassist-3.28.0-GA-remapped.jar:?]
	at org.bukkit.craftbukkit.libs.javassist.CtClass.toClass(CtClass.java:1392) ~[javaassist-3.28.0-GA-remapped.jar:?]
	at org.imanity.rancha.library.LibraryPatches.patchNetty(SourceFile:51) ~[ImanitySpigot3.jar:?]
	at org.imanity.rancha.a.e.d(SourceFile:218) ~[ImanitySpigot3.jar:?]
	at org.imanity.rancha.a.d.a(SourceFile:113) ~[ImanitySpigot3.jar:?]
	at Main.lambda$main$0(SourceFile:166) ~[ImanitySpigot3.jar:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
```

### Plugin list

> pl
[19:03:30 INFO]: [Server thread] Plugins (1): Oneblock (0.8.7+),

### ImanitySpigot3 version

spigotJarVersion: 2021.08.1 BUILD 1

### Agreements

- [X] I am running the latest version of ImanitySpigot3 available from
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have compared the issue inbetween TacoSpigot 1.8.8 and ImanitySpigot3 And only ImanitySpigot3 occured this issue.

**Comment by LeeGodSRC** [comment]
Added a warning message in 2021.08.1 BUILD 5
This error is not patch-able without modifying startup flag, please check https://github.com/Imanity-Software/ImanitySpigot3-git/blob/master/rancha/CHANGELOG.md
