### ISSUE TITLE
Server crashing because of NPE

### ISSUE THREAD

**Issue by ItsClairton** [Imanity-Software/ImanitySpigot3-git#175]
### Stack trace

```java
[00:04:07] [ERROR]: Encountered an unexpected exception
net.minecraft.server.v1_8_R3.ReportedException: Exception ticking world
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(SourceFile:1086) ~[spigot.jar:git-iSpigot-PaperEdition]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(SourceFile:501) ~[spigot.jar:git-iSpigot-PaperEdition]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(SourceFile:938) ~[spigot.jar:git-iSpigot-PaperEdition]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(SourceFile:828) ~[spigot.jar:git-iSpigot-PaperEdition]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_352]
Caused by: java.lang.NullPointerException
	at net.minecraft.server.v1_8_R3.PlayerChunkMap.flush(SourceFile:132) ~[spigot.jar:git-iSpigot-PaperEdition]
	at net.minecraft.server.v1_8_R3.WorldServer.doTick(SourceFile:337) ~[spigot.jar:git-iSpigot-PaperEdition]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(SourceFile:1075) ~[spigot.jar:git-iSpigot-PaperEdition]
	... 4 more
[00:04:07] [ERROR]: 	Cause of unexpected exception was
java.lang.NullPointerException: null
	at net.minecraft.server.v1_8_R3.PlayerChunkMap.flush(SourceFile:132) ~[spigot.jar:git-iSpigot-PaperEdition]
	at net.minecraft.server.v1_8_R3.WorldServer.doTick(SourceFile:337) ~[spigot.jar:git-iSpigot-PaperEdition]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(SourceFile:1075) ~[spigot.jar:git-iSpigot-PaperEdition]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(SourceFile:501) ~[spigot.jar:git-iSpigot-PaperEdition]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(SourceFile:938) ~[spigot.jar:git-iSpigot-PaperEdition]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(SourceFile:828) ~[spigot.jar:git-iSpigot-PaperEdition]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_352]
[00:04:07] [ERROR]: This crash report has been saved to: /home/ubuntu/academy/evento/./crash-reports/crash-2023-01-23_00.04.07-server.txt
[00:04:07] [INFO]: Stopping server
[00:04:07] [INFO]: world - Scheduler shutdown completed.
[00:04:07] [INFO]: [CLCombat] Disabling CLCombat v1.0.0
[00:04:07] [INFO]: [CLRanks] Disabling CLRanks v1.0.0
[00:04:07] [INFO]: [CLEvents] Disabling CLEvents v7bd4607
[00:04:07] [INFO]: [CLAdmin] Disabling CLAdmin v1.0.0
[00:04:07] [INFO]: [CLNoDamageIndicator] Disabling CLNoDamageIndicator v1.0.0
[00:04:07] [INFO]: [WorldEdit] Disabling WorldEdit v6.1.7;dd00bb1
[00:04:07] [INFO]: [ProtocolLib] Disabling ProtocolLib v4.8.0
[00:04:07] [INFO]: [CLLoader] Disabling CLLoader v1.0.0
[00:04:07] [INFO]: [CLFake] Disabling CLFake v1.0.0-PATETA
[00:04:07] [INFO]: [CLObsidian] Disabling CLObsidian v1.0.0
[00:04:07] [INFO]: [654EnchantLapis] Disabling 654EnchantLapis v1.0
[00:04:07] [INFO]: [CLSkins] Disabling CLSkins v1.0.0
[00:04:07] [INFO]: [Packets] Disabling Packets v1.2
[00:04:07] [INFO]: [spark] Disabling spark v1.8.14
[00:04:07] [INFO]: [CLBossBar] Disabling CLBossBar v1.0.0
[00:04:07] [INFO]: [CLCore] Disabling CLCore v1.0.0
[00:04:07] [INFO]: [CLTags] Disabling CLTags v1.0.0
[00:04:07] [INFO]: [FastAsyncWorldEdit] Disabling FastAsyncWorldEdit v19.07.12-5cc5ce5-1277-22.3.0
[00:04:07] [INFO]: [AntiCrash] Disabling AntiCrash v1.0.0
[00:04:07] [INFO]: [CLLockSlot] Disabling CLLockSlot v1.0.0
[00:04:07] [INFO]: [CLCake] Disabling CLCake v1.0.0
[00:04:07] [INFO]: [LuckPerms] Disabling LuckPerms v5.4.30
[00:04:07] [INFO]: [LuckPerms] Starting shutdown process...
[00:04:07] [INFO]: [LuckPerms] Closing messaging service...
[00:04:07] [INFO]: [LuckPerms] Closing storage...
[00:04:07] [INFO]: luckperms-hikari - Shutdown initiated...
[00:04:07] [INFO]: luckperms-hikari - Shutdown completed.
[00:04:07] [INFO]: [LuckPerms] Goodbye!
[00:04:07] [INFO]: [CLChat] Disabling CLChat v1.0.0
[00:04:07] [INFO]: Saving players
[00:04:07] [INFO]: naotenhoperna lost connection: Server closed
[00:04:07] [INFO]: naotenhoperna left the game.
[00:04:07] [INFO]: danielwx lost connection: Server closed
[00:04:07] [INFO]: danielwx left the game.
[00:04:07] [INFO]: Barril100Bebida lost connection: Server closed
[00:04:07] [INFO]: Barril100Bebida left the game.
[00:04:07] [INFO]: Vouladepois lost connection: Server closed
[00:04:07] [INFO]: Vouladepois left the game.
[00:04:07] [INFO]: vinineymar lost connection: Server closed
[00:04:07] [INFO]: vinineymar left the game.
[00:04:07] [INFO]: JuliaaMineGirl lost connection: Server closed
[00:04:07] [INFO]: JuliaaMineGirl left the game.
[00:04:07] [INFO]: lolzinhoptgl lost connection: Server closed
[00:04:07] [INFO]: lolzinhoptgl left the game.
[00:04:07] [INFO]: sctxw lost connection: Server closed
[00:04:07] [INFO]: sctxw left the game.
[00:04:07] [INFO]: potsoaa lost connection: Server closed
[00:04:07] [INFO]: potsoaa left the game.
[00:04:07] [INFO]: feiao lost connection: Server closed
[00:04:07] [INFO]: feiao left the game.
[00:04:07] [INFO]: bexisz lost connection: Server closed
[00:04:07] [INFO]: bexisz left the game.
[00:04:07] [INFO]: Saving worlds
[00:04:07] [INFO]: Saving chunks for level 'world'/Overworld```
```

Crash-log: https://paste.imanity.dev/D31ZQ31

### Plugin list

CLChat (1.0.0), LuckPerms (5.4.30), CLCake (1.0.0), CLLockSlot (1.0.0), AntiCrash (1.0.0), FastAsyncWorldEdit (19.07.12-5cc5ce5-1277-22.3.0), CLTags (1.0.0), CLCore (1.0.0), CLBossBar (1.0.0), spark (1.8.14), Packets (1.2), CLSkins (1.0.0), 654EnchantLapis (1.0), CLObsidian (1.0.0), CLFake (1.0.0-PATETA), CLLoader (1.0.0), ProtocolLib (4.8.0), WorldEdit (6.1.7;dd00bb1), CLNoDamageIndicator (1.0.0), CLAdmin (1.0.0), CLEvents (7bd4607), CLRanks (1.0.0), CLCombat (1.0.0)

### ImanitySpigot3 version

2022.11.1 LTS BUILD 3

### Agreements

- [X] I am running the latest version of ImanitySpigot3 available from
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have compared the issue between TacoSpigot 1.8.8 and ImanitySpigot3 And only ImanitySpigot3 occurred this issue.

### Other

I don't know how it happens, it just happens, and it rarely happens.

**Comment by LeeGodSRC** [comment]
Can it be reproduced without any plugins? We have checked our codes and it seems to be impossible to be produced without any plugin modification

**Comment by ItsClairton** [comment]
I can't say for sure, since it is a very rare situation to happen, it happened 2 times in 26 days (the time we are in imanity).

Talking about our plugins, the only code that deals with chunks via NMS would be this:

```java
        val location = e.getBlockClicked().getRelative(e.getBlockFace()).getLocation();
        Bukkit.getScheduler().runTask(Events.getInstance(), () -> { // Fix ghosting on client-side
            val player = e.getPlayer();

            val world = ((CraftWorld) location.getWorld());
            getChunkPairs(location).forEach(pair -> world.refreshChunk(pair.x, pair.z));

            player.updateInventory();
        });```

```java
    private Collection<ChunkCoordIntPair> getChunkPairs(Location location) {
        int[] offset = {-1,0,1};

        val baseX = location.getChunk().getX();
        val baseZ = location.getChunk().getZ();
        val chunks = new HashSet<ChunkCoordIntPair>();

        for(int x : offset) {
            for(int z : offset) {
                chunks.add(new ChunkCoordIntPair(baseX + x, baseZ + z));
            }
        }

        return chunks;
    }```
    
These codes run after `PlayerBucketFillEvent` or `PlayerBucketEmptyEvent` is cancelled, to avoid phantom buckets on the player's client side.

**Comment by ItsClairton** [comment]
It happened again just now, follow more logs.

Crash-log: https://paste.imanity.dev/Y4OEEsv

Last lines of final logs: https://paste.imanity.dev/FW1mwnq

**Comment by LeeGodSRC** [comment]
Does it still happens if you do not call the refreshChunk?

Also please try it with the latest version of ImanitySpigot3

**Comment by ItsClairton** [comment]
Here's more logs from just one of our rooms.

[crash-2023-03-01_20.45.55-server.txt](https://github.com/Imanity-Software/ImanitySpigot3-git/files/11070372/crash-2023-03-01_20.45.55-server.txt)
[crash-2023-03-11_20.18.46-server.txt](https://github.com/Imanity-Software/ImanitySpigot3-git/files/11070374/crash-2023-03-11_20.18.46-server.txt)
[crash-2023-03-13_00.45.39-server.txt](https://github.com/Imanity-Software/ImanitySpigot3-git/files/11070375/crash-2023-03-13_00.45.39-server.txt)
[crash-2023-03-24_16.47.28-server.txt](https://github.com/Imanity-Software/ImanitySpigot3-git/files/11070376/crash-2023-03-24_16.47.28-server.txt)
[crash-2023-03-25_19.41.36-server.txt](https://github.com/Imanity-Software/ImanitySpigot3-git/files/11070377/crash-2023-03-25_19.41.36-server.txt)
[crash-2023-02-22_18.19.13-server.txt](https://github.com/Imanity-Software/ImanitySpigot3-git/files/11070378/crash-2023-02-22_18.19.13-server.txt)
[crash-2023-02-23_20.16.40-server.txt](https://github.com/Imanity-Software/ImanitySpigot3-git/files/11070379/crash-2023-02-23_20.16.40-server.txt)
[crash-2023-02-24_19.31.40-server.txt](https://github.com/Imanity-Software/ImanitySpigot3-git/files/11070380/crash-2023-02-24_19.31.40-server.txt)
[crash-2023-02-26_16.02.54-server.txt](https://github.com/Imanity-Software/ImanitySpigot3-git/files/11070381/crash-2023-02-26_16.02.54-server.txt)

**Comment by LeeGodSRC** [comment]
Can you with the latest version `2023.03.1 BUILD 2` ?

**Comment by LeeGodSRC** [comment]
Also make sure with compatbilityMode on.

**Comment by ItsClairton** [comment]
```java
[16:17:51] [ERROR]: Could not pass event PlayerMoveEvent to Academy v1.0.0
java.lang.NullPointerException: null
	at it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap$MapIterator.nextEntry(Int2ObjectOpenHashMap.java:703) ~[fastutil-8.5.6.jar:?]
	at it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap$ValueIterator.next(Int2ObjectOpenHashMap.java:1202) ~[fastutil-8.5.6.jar:?]
	at net.minecraft.server.v1_8_R3.EntityTrackerEntry.updatePlayer(SourceFile:630) ~[spigot.jar:git-iSpigot-PaperEdition]
	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.showPlayer(SourceFile:1025) ~[spigot.jar:git-iSpigot-PaperEdition]
	at dev.clairton.bukkit.academy.game.base.Gamer.handleHidePlayers(Gamer.java:105) ~[?:?]
	at dev.clairton.bukkit.academy.game.listener.HiderLIstener.onMove(HiderLIstener.java:18) ~[?:?]
	at org.imanity.imanityspigot.events.executor.asm.generated.GeneratedEventExecutor339.execute(Unknown Source) ~[?:?]
	at org.imanity.imanityspigot.executor.EventExecutorGenerator.lambda$create$1(EventExecutorGenerator.java:62) ~[spigot.jar:git-iSpigot-PaperEdition]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[spigot.jar:git-iSpigot-PaperEdition]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-iSpigot-PaperEdition]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:524) ~[spigot.jar:git-iSpigot-PaperEdition]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:510) ~[spigot.jar:git-iSpigot-PaperEdition]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(SourceFile:409) ~[spigot.jar:git-iSpigot-PaperEdition]
	at net.minecraft.server.v1_8_R3.PacketPlayInFlying.a(SourceFile:31) ~[spigot.jar:git-iSpigot-PaperEdition]
	at net.minecraft.server.v1_8_R3.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:116) ~[spigot.jar:git-iSpigot-PaperEdition]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils.lambda$ensureMainThread$0(SourceFile:52) ~[spigot.jar:git-iSpigot-PaperEdition]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_362]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_362]
	at org.imanity.imanityspigot.final .cM.run(Unknown Source) ~[spigot.jar:git-iSpigot-PaperEdition]
	at org.imanity.imanityspigot.final .cK.executeTask(Unknown Source) ~[spigot.jar:git-iSpigot-PaperEdition]
	at org.imanity.imanityspigot.final .cL.executeTask(Unknown Source) ~[spigot.jar:git-iSpigot-PaperEdition]
	at org.imanity.imanityspigot.final .cK.executeNext(Unknown Source) ~[spigot.jar:git-iSpigot-PaperEdition]
	at net.minecraft.server.v1_8_R3.MinecraftServer.executeNext(SourceFile:1931) ~[spigot.jar:git-iSpigot-PaperEdition]
	at org.imanity.imanityspigot.final .cK.awaitTasks(Unknown Source) ~[spigot.jar:git-iSpigot-PaperEdition]
	at net.minecraft.server.v1_8_R3.MinecraftServer.sleepForTick(SourceFile:1904) ~[spigot.jar:git-iSpigot-PaperEdition]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(SourceFile:840) ~[spigot.jar:git-iSpigot-PaperEdition]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_362]```
	
![image](https://user-images.githubusercontent.com/28469592/229310785-1f98a399-1f7e-487a-b2d1-4f29793988ff.png)

**Comment by ItsClairton** [comment]
Yeap, crashed again: https://paste.imanity.dev/Ny91e3w

**Comment by ItsClairton** [comment]
```java
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 65
	at it.unimi.dsi.fastutil.longs.LongOpenHashSet.rehash(LongOpenHashSet.java:872)
	at it.unimi.dsi.fastutil.longs.LongOpenHashSet.add(LongOpenHashSet.java:433)
	at org.imanity.imanityspigot.final .cV.b(Unknown Source)
	at org.imanity.imanityspigot.final .cV.remove(Unknown Source)
	at org.imanity.imanityspigot.final .cV$a.remove(Unknown Source)
	at net.minecraft.server.v1_8_R3.ChunkProviderServer.unloadChunks(SourceFile:780)
	at net.minecraft.server.v1_8_R3.WorldServer.doTick(SourceFile:315)
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(SourceFile:1084)
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(SourceFile:502)
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(SourceFile:947)
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(SourceFile:837)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by interable** [comment]
it's caused by accessing chunks and entity tracker asynchronously, if a chunk is accessed, spigot remove their coordinate from queue that contains all chunks that is about to unload, if chunk is accessed asynchronously - desync happens, so entire hashtable is broken
