### ISSUE TITLE
ImanitySpigot 與 Citizens 不相容 

### ISSUE THREAD

**Issue by GoodestEnglish** [Imanity-Software/ImanitySpigot3-git#184]
### Expected behavior 預期狀況

玩家能夠攻擊沒有受保護的Citizens NPC

### Observed/Actual behavior 實際狀況

在開啟伺服器時, Citizens 報錯了以下的錯誤:
```[21:21:04 WARN]: [Citizens] Task #21 for Citizens v2.0.30-SNAPSHOT (build 2960) generated an exception
java.lang.NullPointerException: null
        at org.imanity.imanityspigot.final .h.c(Unknown Source) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.World.removeEntity(SourceFile:1608) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.citizensnpcs.nms.v1_8_R3.util.NMSImpl.removeFromWorld(NMSImpl.java:932) ~[?:?]
        at net.citizensnpcs.util.NMS.removeFromWorld(NMS.java:571) ~[?:?]
        at net.citizensnpcs.npc.AbstractEntityController.remove(AbstractEntityController.java:44) ~[?:?]
        at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:322) ~[?:?]
        at net.citizensnpcs.npc.CitizensNPC.load(CitizensNPC.java:183) ~[?:?]
        at net.citizensnpcs.api.npc.SimpleNPCDataStore.loadInto(SimpleNPCDataStore.java:59) ~[?:?]
        at net.citizensnpcs.Citizens$CitizensLoadTask.run(Citizens.java:620) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(SourceFile:59) ~[spigot.jar:git-iSpigot-PaperEdition]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(SourceFile:410) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(SourceFile:1033) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(SourceFile:501) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(SourceFile:945) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(SourceFile:835) ~[spigot.jar:git-iSpigot-PaperEdition]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
```

這個錯誤導致玩家無法攻擊Citizens NPC, 以下是PaperSpigot 和ImanitySpigot 的對比:
https://youtu.be/JKeScUjeYn0

### Steps/models to reproduce 重現的方式

使用Citizens 並且以下指令:
/npc create hi
/npc vulnerable

然後攻擊NPC

### Plugin list 插件列表

FastAsyncWorldEdit (19.11.13-5505943-1282-22.3.5)
ViaVersion (4.4.2)
IPWhitelist (1.7)
PlaceholderAPI (2.11.2)
ProtocolLib (4.8.0)
ViaRewind (2.0.2)
Citizens (2.0.30-SNAPSHOT (build 2960))
WorldEdit (6.1.7;dd00bb1)
Eden (1.0.38-BETA-b3dcdbf)
BungeeGuard (1.2-SNAPSHOT)
Eden-PvPBot (${version})
spark (1.10.32)

### ImanitySpigot3 的版本

2023.02.1 LTS BUILD 6

### Agreements 同意事項

- [X] 我目前運行的 ImanitySpigot3 版本在 #imanityspigot 頻道中有顯示在 正在支援 的版本列表裡.
- [X] 我有在這個 Issue Tracker 中搜尋過並沒有發現類似的問題回報.
- [X] 我已經把原版的 TacoSpigot 1.8.8 和 ImanitySpigot3 互相比較過並且確定只有 ImanitySpigot3 會發生這個問題.

**Comment by LeeGodSRC** [comment]
disable server side hit detection should get the issue fixed
Do not turn server side hit detection on yet as the feature is still a WIP
(we are consider to remove it soon and add it back in another form)
