### ISSUE TITLE
PlotSquared issue 2

### ISSUE THREAD

**Issue by FixYourWork** [Imanity-Software/ImanitySpigot3-git#196]
### Expected behavior

Not seeing WARN in console.
** Taco spigot is still fine **

### Observed/Actual behavior

[00:29:22] [WARN]: Exception in thread "Craft Scheduler Thread - 1" org.apache.commons.lang.UnhandledException: Plugin PlotSquared v3.5.0-SNAPSHOT-2b561f2 generated an exception while executing task 9
[00:29:22] [WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(SourceFile:57)
[00:29:22] [WARN]: 	at org.github.paperspigot.ServerSchedulerReportingWrapper.run(SourceFile:22)
[00:29:22] [WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[00:29:22] [WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[00:29:22] [WARN]: 	at java.lang.Thread.run(Unknown Source)
[00:29:22] [WARN]: Caused by: java.lang.NullPointerException
[00:29:22] [WARN]: 	at com.intellectualcrafters.plot.database.SQLManager$14.set(SQLManager.java:994)
[00:29:22] [WARN]: 	at com.intellectualcrafters.plot.database.SQLManager.sendBatch(SQLManager.java:332)
[00:29:22] [WARN]: 	at com.intellectualcrafters.plot.database.SQLManager$1.run(SQLManager.java:140)
[00:29:22] [WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(SourceFile:59)
[00:29:22] [WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(SourceFile:53)
[00:29:22] [WARN]: 	... 4 more

### Steps/models to reproduce

Idk fix the problem

### Plugin list

PlotSquared, Vault, WorldGuard, WorldEdit

### ImanitySpigot3 version

spigotJarVersion: 2023.03.1 BUILD 3

### Agreements

- [X] I am running the latest version of ImanitySpigot3 available from
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have compared the issue between TacoSpigot 1.8.8 and ImanitySpigot3 And only ImanitySpigot3 occurred this issue.

**Comment by LeeGodSRC** [comment]
unfortunately we can't see anything that is possibily related to ImanitySpigot3, the error seems to come from PlotSquared's SQL database having NPE
