### ISSUE TITLE
[BUG] iSpigot merge to latest Netty causing Direct Buffer exception

### ISSUE THREAD

**Issue by terminalsin** [Imanity-Software/ImanitySpigot3-git#2]
**Expected behavior**
A clean and calm console. Just joking. Netty has a function in ByteBuf#array which provides a byte array containing all the byte information from a buffer. 

**Observed/Actual behavior**
In iSpigot, the use of latter netty version (which deprecated this function by causing direct `java.lang.UnsupportedOperationException: direct buffer` exceptions) causes incompatibilities. This will be problematic as the StringPool netty converter _requires_ this for sub 1.12. 

**Steps/models to reproduce**
Here's the String pool reader from my Packet API:

```java
package cc.ghast.packet.buffer.types.exclusive;

import ac.artemis.packet.protocol.ProtocolVersion;
import cc.ghast.packet.buffer.BufConverter;
import cc.ghast.packet.buffer.types.Converters;
import cc.ghast.packet.wrapper.codec.StringPool;
import cc.ghast.packet.wrapper.netty.MutableByteBuf;
import com.google.common.base.Charsets;
import io.netty.handler.codec.DecoderException;
import io.netty.handler.codec.EncoderException;

import java.nio.charset.StandardCharsets;


public class StringPoolConverter extends BufConverter<StringPool> {
    public StringPoolConverter() {
        super("StringPool", StringPool.class);
    }

    @Override
    public void write(MutableByteBuf buffer, StringPool value) {
        byte[] abyte = value.getData().getBytes(Charsets.UTF_8);
        if (abyte.length > 32767) {
            throw new EncoderException("String too big (was " + value.getData().length() + " bytes encoded, max " + 32767 + ")");
        } else {
            Converters.VAR_INT.write(buffer, abyte.length);
            buffer.writeBytes(abyte);
        }
    }

    @Override
    public StringPool read(MutableByteBuf buffer, ProtocolVersion version, Object... args) {
        if (args.length < 1) throw new DecoderException("The received string is supposed to have getX size");
        int max = (int) args[0];
        int length = Converters.VAR_INT.read(buffer, version);
        if (length > max * 4) {
            throw new DecoderException("The received encoded string buffer length is longer than maximum allowed (" + length + " > " + max * 4 + ")");
        }

        if (length < 0) {
            throw new DecoderException("The received encoded string buffer length is less than zero! Weird string!");
        }

        String s;

        if (version.isOrAbove(ProtocolVersion.V1_12)) {
            s = buffer.toString(buffer.readerIndex(), length, StandardCharsets.UTF_8);
            buffer.readerIndex(buffer.readerIndex() + length);
        } else {
            s = new String(buffer.readBytes(length).array(), Charsets.UTF_8);
        }

        if (s.length() > max) {
            throw new DecoderException("The received string length is longer than maximum allowed (" + length + " > " + max + ")");
        }

        return new StringPool(s, length);
    }
}

```

Effectively, the only interesting bit is the following line of code:

```java
s = new String(buffer.readBytes(length).array(), Charsets.UTF_8);
```

**Plugin list**
Artemis (:P)

**ImanitySpigot3 version**
2021.06.1 BUILD 2

**Please agree to the following.  (fill x in the [ ])**
- [x] I am running the latest version of Paper available from /#client-info channel in our discord.
- [x] I have searched for and ensured there isn't already an open issue regarding this.
- [x] I have compared the issue inbetween TacoSpigot 1.8.8 and ImanitySpigot3 And only ImanitySpigot3 occured this issue.

**Additional context**
Here's the stacktrace:

```
[17:00:55 INFO]: [ Server IO #3] Error on packet of player of version V1_8_9
[17:00:55 WARN]: [ Server IO #3] java.lang.UnsupportedOperationException: direct buffer
[17:00:55 WARN]: [ Server IO #3]        at io.netty.buffer.PooledUnsafeDirectByteBuf.array(PooledUnsafeDirectByteBuf.java:226)
[17:00:55 WARN]: [ Server IO #3]        at cc.ghast.packet.artemusjz.array(artemusjz.java:738)
[17:00:55 WARN]: [ Server IO #3]        at cc.ghast.packet.artemusso.artemusa(artemusso.java:50)
[17:00:55 WARN]: [ Server IO #3]        at cc.ghast.packet.artemusni.artemusa(artemusni.java:90)
[17:00:55 WARN]: [ Server IO #3]        at cc.ghast.packet.artemusiH.read(artemusiH.java:38)
[17:00:55 WARN]: [ Server IO #3]        at cc.ghast.packet.artemusN.artemusa(artemusN.java:204)
[17:00:55 WARN]: [ Server IO #3]        at cc.ghast.packet.artemusN.artemusa(artemusN.java:87)
[17:00:55 WARN]: [ Server IO #3]        at cc.ghast.packet.artemusN.write(artemusN.java:67)
[17:00:55 WARN]: [ Server IO #3]        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[17:00:55 WARN]: [ Server IO #3]        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[17:00:55 WARN]: [ Server IO #3]        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[17:00:55 WARN]: [ Server IO #3]        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[17:00:55 WARN]: [ Server IO #3]        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[17:00:55 WARN]: [ Server IO #3]        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[17:00:55 WARN]: [ Server IO #3]        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[17:00:55 WARN]: [ Server IO #3]        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[17:00:55 WARN]: [ Server IO #3]        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[17:00:55 WARN]: [ Server IO #3]        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
[17:00:55 WARN]: [ Server IO #3]        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[17:00:55 WARN]: [ Server IO #3]        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[17:00:55 WARN]: [ Server IO #3]        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[17:00:55 WARN]: [ Server IO #3]        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[17:00:55 WARN]: [ Server IO #3]        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[17:00:55 WARN]: [ Server IO #3]        at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:275)
[17:00:55 WARN]: [ Server IO #3]        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[17:00:55 WARN]: [ Server IO #3]        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[17:00:55 WARN]: [ Server IO #3]        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[17:00:55 WARN]: [ Server IO #3]        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[17:00:55 WARN]: [ Server IO #3]        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:110)
[17:00:55 WARN]: [ Server IO #3]        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[17:00:55 WARN]: [ Server IO #3]        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[17:00:55 WARN]: [ Server IO #3]        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[17:00:55 WARN]: [ Server IO #3]        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[17:00:55 WARN]: [ Server IO #3]        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
[17:00:55 WARN]: [ Server IO #3]        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[17:00:55 WARN]: [ Server IO #3]        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[17:00:55 WARN]: [ Server IO #3]        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[17:00:55 WARN]: [ Server IO #3]        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[17:00:55 WARN]: [ Server IO #3]        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
[17:00:55 WARN]: [ Server IO #3]        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[17:00:55 WARN]: [ Server IO #3]        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:294)
[17:00:55 WARN]: [ Server IO #3]        at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[17:00:55 WARN]: [ Server IO #3]        at net.minecraft.server.v1_8_R3.NetworkManager$4.run(SourceFile:214)
[17:00:55 WARN]: [ Server IO #3]        at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:352)
[17:00:55 WARN]: [ Server IO #3]        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[17:00:55 WARN]: [ Server IO #3]        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
[17:00:55 WARN]: [ Server IO #3]        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
[17:00:55 WARN]: [ Server IO #3]        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[17:00:55 WARN]: [ Server IO #3]        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[17:00:55 WARN]: [ Server IO #3]        at java.lang.Thread.run(Thread.java:748)
```

**Comment by LeeGodSRC** [comment]
I'm not really understand how netty works exactly
But it seems like netty still returns direct buffer while readBytes were occured in newer netty version
When in older versions netty allocate heap buffer instead
(Not sure if i'm correct)

I've added an option to let netty not preferring direct buffer enabled by default in **2021.06.1 BUILD 3**
Can you please try it again?

**Comment by LeeGodSRC** [comment]
after adding the option this issue seems fine now, will close this issue for now
