### ISSUE TITLE
re light

### ISSUE THREAD

**Issue by vSKAH** [Imanity-Software/ImanitySpigot3-git#213]
### Message d'erreur en console

```
[17:43:10 INFO]: vSKAH issued server command: /ispigot relight 200
[17:43:15 ERROR]: Thread Imanity Threading Engine occurs an error: null
java.lang.IllegalStateException: null
        at org.imanity.imanityspigot.final .cz.a(Unknown Source) ~[spigot.jar:git-iSpigot-PaperEdition]
        at org.imanity.imanityspigot.final .cA.a(Unknown Source) ~[spigot.jar:git-iSpigot-PaperEdition]
        at org.imanity.imanityspigot.final .co.b(Unknown Source) ~[spigot.jar:git-iSpigot-PaperEdition]
        at org.imanity.imanityspigot.h$a.run(Unknown Source) ~[spigot.jar:git-iSpigot-PaperEdition]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Liste des plugins

Aucun

### Etapes pour reproduire le problème (si vous le savez)

/imanity relight 200.
Il y a une certaine chance d'avoir cette erreur

### ImanitySpigot3 version

2023.05.1 LTS BUILD 3

### Accords

- [X] J'utilise la dernière version d'ImanitySpigot3 disponible depuis le salon
- [X] J'ai fais des recherches afin d'être certains qu'il n'y est pas déjà une "issue" ouverte à ce sujet.
- [X] J'ai fais des comparaisons du problème entre TacoSpigot 1.8.8 et ImanitySpigot3. Et ce problème se produit seulement avec ImanitySpigot3.

**Comment by Xefreh** [comment]
Issue closed. Issue has been solved in one of update of fastlightengine.
