### ISSUE TITLE
PluginManager issue

### ISSUE THREAD

**Issue by vSKAH** [Imanity-Software/ImanitySpigot3-git#236]
### Stack trace

```
[18:46:21 INFO]: vSKAH issued server command: /pluginmanager reload LF-Items
[18:46:21 INFO]: [LF-Items] Disabling LF-Items v1.0.0
[18:46:21 INFO]: [LF-Items] Items cleared !
[18:46:21 INFO]: [LF-Items] Rarities cleared !
[18:46:21 INFO]: [LF-Items] ElevatorManager saved !
[18:46:21 INFO]: [LF-Items] FWaystoneManager saved !
[18:46:21 INFO]: [LF-Items] FWaystoneRenderer cleared !
[18:46:21 INFO]: [LF-Items] BlockTickableManager saved !
[18:46:21 INFO]: [LF-Items] ProtocolManager cleared !
[18:46:21 INFO]: [LF-Items] Commands cleared !
[18:46:21 INFO]: [LF-Items] Listeners cleared !
[18:46:21 INFO]: [LF-Items] Tasks cleared !
[18:46:21 WARN]: org.bukkit.plugin.InvalidPluginException: java.lang.IllegalArgumentException: Plugin already initialized!
[18:46:21 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:134)
[18:46:21 WARN]:        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:314)
[18:46:21 WARN]:        at org.imanity.imanityspigot.final .ce.a(Unknown Source)
[18:46:21 WARN]:        at org.imanity.imanityspigot.final .ce.execute(Unknown Source)
[18:46:21 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:144)
[18:46:21 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(SourceFile:746)
[18:46:21 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(SourceFile:1427)
[18:46:21 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.a(SourceFile:1239)
[18:46:21 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(SourceFile:59)
[18:46:21 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(SourceFile:15)
[18:46:21 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils.lambda$ensureMainThread$0(SourceFile:52)
[18:46:21 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
[18:46:21 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[18:46:21 WARN]:        at org.imanity.imanityspigot.final .db.run(Unknown Source)
[18:46:21 WARN]:        at org.imanity.imanityspigot.final .cZ.executeTask(Unknown Source)
[18:46:21 WARN]:        at org.imanity.imanityspigot.final .da.executeTask(Unknown Source)
[18:46:21 WARN]:        at org.imanity.imanityspigot.final .cZ.executeNext(Unknown Source)
[18:46:21 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.executeNext(SourceFile:1954)
[18:46:21 WARN]:        at org.imanity.imanityspigot.final .cZ.awaitTasks(Unknown Source)
[18:46:21 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.sleepForTick(SourceFile:1927)
[18:46:21 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(SourceFile:863)
[18:46:21 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1589)
[18:46:21 WARN]: Caused by: java.lang.IllegalArgumentException: Plugin already initialized!
[18:46:21 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.initialize(PluginClassLoader.java:123)
[18:46:21 WARN]:        at org.bukkit.plugin.java.JavaPlugin.<init>(JavaPlugin.java:66)
[18:46:21 WARN]:        at fr.skah.lastfight.items.LFItems.<init>(LFItems.java:54)
[18:46:21 WARN]:        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
[18:46:21 WARN]:        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
[18:46:21 WARN]:        at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128)
[18:46:21 WARN]:        at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:306)
[18:46:21 WARN]:        at java.base/java.lang.Class.newInstance(Class.java:684)
[18:46:21 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:77)
[18:46:21 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:130)
[18:46:21 WARN]:        ... 21 more
[18:46:21 WARN]: Caused by: java.lang.IllegalStateException: Initial initialization
[18:46:21 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.initialize(PluginClassLoader.java:126)
[18:46:21 WARN]:        at org.bukkit.plugin.java.JavaPlugin.<init>(JavaPlugin.java:66)
[18:46:21 WARN]:        at fr.skah.lastfight.items.LFItems.<init>(LFItems.java:54)
[18:46:21 WARN]:        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
[18:46:21 WARN]:        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
[18:46:21 WARN]:        at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128)
[18:46:21 WARN]:        at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:306)
[18:46:21 WARN]:        at java.base/java.lang.Class.newInstance(Class.java:684)
[18:46:21 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:77)
[18:46:21 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:130)
[18:46:21 WARN]:        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:314)
[18:46:21 WARN]:        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:246)
[18:46:21 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(SourceFile:335)
[18:46:21 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.init(SourceFile:324)
[18:46:21 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(SourceFile:757)
[18:46:21 WARN]:        ... 1 more

```

LFItems.java:54 is class delcaration:

```JAVA
public class LFItems extends JavaPlugin {
```

### Plugin list

LF-Items, ProtocolLib, Faction UUID

### Steps/models to reproduce (if known)

i have just used command /pluginmanager reload LF-Items

### ImanitySpigot3 version

2024.03.1 LTS BUILD 4

### Agreements

- [X] I am running the latest version of ImanitySpigot3 available from
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have compared the issue between TacoSpigot 1.8.8 and ImanitySpigot3 And only ImanitySpigot3 occurred this issue.

**Comment by Xefreh** [comment]
Issue closed not imanity's fault, plugins seems to not support reloading.
