### ISSUE TITLE
/clear won't clear the armor slot

### ISSUE THREAD

**Issue by HappyAreaBean** [Imanity-Software/ImanitySpigot3-git#25]
### Stack trace

```
[22:26:17 WARN]: [Server thread] Unknown CommandBlock failed to handle command
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 4
        at net.minecraft.server.v1_8_R3.EntityHuman.setEquipment(SourceFile:1712) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.PlayerInventory.a(SourceFile:147) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.CommandClear.execute(CommandClear.java:43) ~[spigot.jar:git-iSpigot-PaperEdition]
        at org.bukkit.craftbukkit.v1_8_R3.command.VanillaCommandWrapper.dispatchVanillaCommand(SourceFile:123) ~[spigot.jar:git-iSpigot-PaperEdition]
        at org.bukkit.craftbukkit.v1_8_R3.command.VanillaCommandWrapper.execute(SourceFile:44) ~[spigot.jar:git-iSpigot-PaperEdition]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:143) ~[spigot.jar:git-iSpigot-PaperEdition]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(SourceFile:681) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(SourceFile:1231) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(SourceFile:1043) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(SourceFile:43) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(SourceFile:9) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(PlayerConnectionUtils.java:16) ~[spigot.jar:git-iSpigot-PaperEdition]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:18) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(SourceFile:890) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(SourceFile:447) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(SourceFile:821) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(SourceFile:723) ~[spigot.jar:git-iSpigot-PaperEdition]
        at java.lang.Thread.run(Thread.java:829) [?:?]
```

### Plugin list

N/A

### Steps/models to reproduce (if known)

1. Let your armor slot have items/armor
2. Type /clear
3. If your inventory have items they can be cleared but it won't clear the armor slot
The armor slot will show like this
![img](https://cdn.discordapp.com/attachments/821728933631229952/881187449139761233/unknown.png)

### ImanitySpigot3 version

2021.08.1 BUILD 7

### Agreements

- [X] I am running the latest version of ImanitySpigot3 available from
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have compared the issue inbetween TacoSpigot 1.8.8 and ImanitySpigot3 And only ImanitySpigot3 occured this issue.

**Comment by LeeGodSRC** [comment]
This issue will be fixed in **2021.08.1 BUILD 8**
