### ISSUE TITLE
JavaAssist ClassNotFoundException when using older Citizens2 build (2.0.16-SNAPSHOT (build 1267))

### ISSUE THREAD

**Issue by Luzzrood** [Imanity-Software/ImanitySpigot3-git#30]
### Comportement attendu

Le plugin ne se load pas

### Comportement actuel/observé

org.bukkit.craftbukkit.libs.javassist.NotFoundException: net.citizensnpcs.nms.v1_8_R3.network.EmptyChannel
	at org.bukkit.craftbukkit.libs.javassist.ClassPool.get(ClassPool.java:430) ~[javaassist-3.28.0-GA-remapped.jar:?]
	at org.imanity.imanityspigot.c.d(SourceFile:156) ~[spigot.jar:git-iSpigot-PaperEdition]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604) ~[?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]

### Etapes pour reproduire le problème

utiliser citizens2

### Liste des plugins

Citizens

### ImanitySpigot3 version

2021.08.1 BUILD 8

### Accords

- [X] J'utilise la dernière version d'ImanitySpigot3 disponible depuis le salon
- [X] J'ai fais des recherches afin d'être certains qu'il n'y est pas déjà une "issue" ouverte à ce sujet.
- [X] J'ai fais des comparaisons du problème entre TacoSpigot 1.8.8 et ImanitySpigot3. Et ce problème se produit seulement avec ImanitySpigot3.

**Comment by LeeGodSRC** [comment]
What Citizens build you were using?

**Comment by Luzzrood** [comment]
2.0.16-SNAPSHOT (build 1267)
