### ISSUE TITLE
無法使用/knockback

### ISSUE THREAD

**Issue by NwTW** [Imanity-Software/ImanitySpigot3-git#31]
### Expected behavior 預期狀況

knockback指令運作正常

### Observed/Actual behavior 實際狀況

當我使用/kb或是/knockback指令時後臺會報錯

### Steps/models to reproduce 重現的方式

[23:11:49 INFO]: [Server thread] Nw_Tohka_TW issued server command: /kb
[23:11:49 ERROR]: [Server thread] null
org.bukkit.command.CommandException: Unhandled exception executing 'kb' in org.imanity.imanityspigot.knockback.command.c(knockback)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:150) ~[spigot.jar:git-iSpigot-PaperEdition]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(SourceFile:714) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(SourceFile:1316) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(SourceFile:1128) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(SourceFile:47) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(SourceFile:13) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:21) ~[spigot.jar:git-iSpigot-PaperEdition]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_302]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_302]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:18) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(SourceFile:939) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(SourceFile:471) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(SourceFile:869) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(SourceFile:770) ~[spigot.jar:git-iSpigot-PaperEdition]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_302]
Caused by: java.lang.IllegalArgumentException: Duplicate handler name: Nw_Tohka_TW
        at io.netty.channel.DefaultChannelPipeline.checkDuplicateName(DefaultChannelPipeline.java:1055) ~[netty-4.1.60.Final.jar:4.1.60.Final]
        at io.netty.channel.DefaultChannelPipeline.filterName(DefaultChannelPipeline.java:284) ~[netty-4.1.60.Final.jar:4.1.60.Final]
        at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:247) ~[netty-4.1.60.Final.jar:4.1.60.Final]
        at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:237) ~[netty-4.1.60.Final.jar:4.1.60.Final]
        at com.comphenix.protocol.injector.netty.PipelineProxy.addBefore(PipelineProxy.java:61) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3$1.addBefore(ChannelInjector.java:314) ~[?:?]
        at org.imanity.imanityspigot.db.c(SourceFile:68) ~[spigot.jar:git-iSpigot-PaperEdition]
        at org.imanity.imanityspigot.db.a(SourceFile:33) ~[spigot.jar:git-iSpigot-PaperEdition]
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660) ~[?:1.8.0_302]
        at org.imanity.imanityspigot.db.a(SourceFile:33) ~[spigot.jar:git-iSpigot-PaperEdition]
        at org.imanity.imanityspigot.cG.b(SourceFile:79) ~[spigot.jar:git-iSpigot-PaperEdition]
        at org.imanity.imanityspigot.cD.a(SourceFile:83) ~[spigot.jar:git-iSpigot-PaperEdition]
        at org.imanity.imanityspigot.ch.a(SourceFile:34) ~[spigot.jar:git-iSpigot-PaperEdition]
        at org.imanity.imanityspigot.knockback.command.c.execute(SourceFile:60) ~[spigot.jar:git-iSpigot-PaperEdition]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:143) ~[spigot.jar:git-iSpigot-PaperEdition]
        ... 14 more
[23:12:06 WARN]: [er Thread - 2] Exception in thread "Craft Scheduler Thread - 2" org.apache.commons.lang.UnhandledException: Plugin PlaceholderAPI v2.10.9 generated an exception while executing task 8467
[23:12:06 WARN]: [er Thread - 2]        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(SourceFile:57)
[23:12:06 WARN]: [er Thread - 2]        at org.github.paperspigot.ServerSchedulerReportingWrapper.run(SourceFile:22)
[23:12:06 WARN]: [er Thread - 2]        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[23:12:06 WARN]: [er Thread - 2]        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[23:12:06 WARN]: [er Thread - 2]        at java.lang.Thread.run(Thread.java:748)
[23:12:06 WARN]: [er Thread - 2] Caused by: java.lang.NullPointerException
[23:12:06 WARN]: [er Thread - 2]        at me.scruffyboy13.Economy.utils.EconomyUtils.getBalance(EconomyUtils.java:168)
[23:12:06 WARN]: [er Thread - 2]        at com.extendedclip.papi.expansion.vault.VaultEcoHook.getBalance(VaultEcoHook.java:220)
[23:12:06 WARN]: [er Thread - 2]        at com.extendedclip.papi.expansion.vault.BalTopTask.run(BalTopTask.java:48)
[23:12:06 WARN]: [er Thread - 2]        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(SourceFile:59)
[23:12:06 WARN]: [er Thread - 2]        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(SourceFile:53)
[23:12:06 WARN]: [er Thread - 2]        ... 4 more

![2021-09-18_23 11 51](https://user-images.githubusercontent.com/80190796/133893643-0caaddd8-e91e-46c9-ab09-a33883855dad.png)
[latest.log](https://github.com/Imanity-Software/ImanitySpigot3-git/files/7190165/latest.log)

### Plugin list 插件列表

.

### ImanitySpigot3 的版本

2021.09.2 BUILD 1

### Agreements 同意事項

- [X] 我目前運行的 ImanitySpigot3 版本在 #client-info 頻道中有顯示在 正在支援 的版本列表裡.
- [X] 我有在這個 Issue Tracker 中搜尋過並沒有發現類似的問題回報.
- [X] 我已經把原版的 TacoSpigot 1.8.8 和 ImanitySpigot3 互相比較過並且確定只有 ImanitySpigot3 會發生這個問題.

### Others 額外資訊

none

**Comment by NwTW** [comment]
> ### Expected behavior 預期狀況
> knockback指令運作正常
> 
> ### Observed/Actual behavior 實際狀況
> 當我使用/kb或是/knockback指令時後臺會報錯
> 
> ### Steps/models to reproduce 重現的方式
> [23:11:49 INFO]: [Server thread] Nw_Tohka_TW issued server command: /kb
> [23:11:49 ERROR]: [Server thread] null
> org.bukkit.command.CommandException: Unhandled exception executing 'kb' in org.imanity.imanityspigot.knockback.command.c(knockback)
> at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:150) ~[spigot.jar:git-iSpigot-PaperEdition]
> at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(SourceFile:714) ~[spigot.jar:git-iSpigot-PaperEdition]
> at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(SourceFile:1316) ~[spigot.jar:git-iSpigot-PaperEdition]
> at net.minecraft.server.v1_8_R3.PlayerConnection.a(SourceFile:1128) ~[spigot.jar:git-iSpigot-PaperEdition]
> at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(SourceFile:47) ~[spigot.jar:git-iSpigot-PaperEdition]
> at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(SourceFile:13) ~[spigot.jar:git-iSpigot-PaperEdition]
> at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:21) ~[spigot.jar:git-iSpigot-PaperEdition]
> at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_302]
> at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_302]
> at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:18) ~[spigot.jar:git-iSpigot-PaperEdition]
> at net.minecraft.server.v1_8_R3.MinecraftServer.B(SourceFile:939) ~[spigot.jar:git-iSpigot-PaperEdition]
> at net.minecraft.server.v1_8_R3.DedicatedServer.B(SourceFile:471) ~[spigot.jar:git-iSpigot-PaperEdition]
> at net.minecraft.server.v1_8_R3.MinecraftServer.A(SourceFile:869) ~[spigot.jar:git-iSpigot-PaperEdition]
> at net.minecraft.server.v1_8_R3.MinecraftServer.run(SourceFile:770) ~[spigot.jar:git-iSpigot-PaperEdition]
> at java.lang.Thread.run(Thread.java:748) [?:1.8.0_302]
> Caused by: java.lang.IllegalArgumentException: Duplicate handler name: Nw_Tohka_TW
> at io.netty.channel.DefaultChannelPipeline.checkDuplicateName(DefaultChannelPipeline.java:1055) ~[netty-4.1.60.Final.jar:4.1.60.Final]
> at io.netty.channel.DefaultChannelPipeline.filterName(DefaultChannelPipeline.java:284) ~[netty-4.1.60.Final.jar:4.1.60.Final]
> at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:247) ~[netty-4.1.60.Final.jar:4.1.60.Final]
> at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:237) ~[netty-4.1.60.Final.jar:4.1.60.Final]
> at com.comphenix.protocol.injector.netty.PipelineProxy.addBefore(PipelineProxy.java:61) ~[?:?]
> at com.comphenix.protocol.injector.netty.ChannelInjector$3$1.addBefore(ChannelInjector.java:314) ~[?:?]
> at org.imanity.imanityspigot.db.c(SourceFile:68) ~[spigot.jar:git-iSpigot-PaperEdition]
> at org.imanity.imanityspigot.db.a(SourceFile:33) ~[spigot.jar:git-iSpigot-PaperEdition]
> at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660) ~[?:1.8.0_302]
> at org.imanity.imanityspigot.db.a(SourceFile:33) ~[spigot.jar:git-iSpigot-PaperEdition]
> at org.imanity.imanityspigot.cG.b(SourceFile:79) ~[spigot.jar:git-iSpigot-PaperEdition]
> at org.imanity.imanityspigot.cD.a(SourceFile:83) ~[spigot.jar:git-iSpigot-PaperEdition]
> at org.imanity.imanityspigot.ch.a(SourceFile:34) ~[spigot.jar:git-iSpigot-PaperEdition]
> at org.imanity.imanityspigot.knockback.command.c.execute(SourceFile:60) ~[spigot.jar:git-iSpigot-PaperEdition]
> at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:143) ~[spigot.jar:git-iSpigot-PaperEdition]
> ... 14 more
> [23:12:06 WARN]: [er Thread - 2] Exception in thread "Craft Scheduler Thread - 2" org.apache.commons.lang.UnhandledException: Plugin PlaceholderAPI v2.10.9 generated an exception while executing task 8467
> [23:12:06 WARN]: [er Thread - 2] at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(SourceFile:57)
> [23:12:06 WARN]: [er Thread - 2] at org.github.paperspigot.ServerSchedulerReportingWrapper.run(SourceFile:22)
> [23:12:06 WARN]: [er Thread - 2] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> [23:12:06 WARN]: [er Thread - 2] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> [23:12:06 WARN]: [er Thread - 2] at java.lang.Thread.run(Thread.java:748)
> [23:12:06 WARN]: [er Thread - 2] Caused by: java.lang.NullPointerException
> [23:12:06 WARN]: [er Thread - 2] at me.scruffyboy13.Economy.utils.EconomyUtils.getBalance(EconomyUtils.java:168)
> [23:12:06 WARN]: [er Thread - 2] at com.extendedclip.papi.expansion.vault.VaultEcoHook.getBalance(VaultEcoHook.java:220)
> [23:12:06 WARN]: [er Thread - 2] at com.extendedclip.papi.expansion.vault.BalTopTask.run(BalTopTask.java:48)
> [23:12:06 WARN]: [er Thread - 2] at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(SourceFile:59)
> [23:12:06 WARN]: [er Thread - 2] at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(SourceFile:53)
> [23:12:06 WARN]: [er Thread - 2] ... 4 more
> 
> ![2021-09-18_23 11 51](https://user-images.githubusercontent.com/80190796/133893643-0caaddd8-e91e-46c9-ab09-a33883855dad.png)
> [latest.log](https://github.com/Imanity-Software/ImanitySpigot3-git/files/7190165/latest.log)
> 
> ### Plugin list 插件列表
>.
> 
> ### ImanitySpigot3 的版本
> 2021.09.2 BUILD 1
> 
> ### Agreements 同意事項
> * [x]  我目前運行的 ImanitySpigot3 版本在 #client-info 頻道中有顯示在 正在支援 的版本列表裡.
> * [x]  我有在這個 Issue Tracker 中搜尋過並沒有發現類似的問題回報.
> * [x]  我已經把原版的 TacoSpigot 1.8.8 和 ImanitySpigot3 互相比較過並且確定只有 ImanitySpigot3 會發生這個問題.
> 
> ### Others 額外資訊
> none

**Comment by LeeGodSRC** [comment]
該問題將於版本 ``2021.09.2b2`` 中修復並將在不久後推出.
