### ISSUE TITLE
Error on server stop

### ISSUE THREAD

**Issue by ZeyKoYT** [Imanity-Software/ImanitySpigot3-git#38]
### Stack trace

```
[18:46:15 WARN]: Exception in thread "pool-23-thread-1" java.lang.RuntimeException: java.lang.InterruptedException
[18:46:15 WARN]:        at net.minecraft.server.v1_8_R3.ImanityAsyncChunkProvider.getChunkAt(SourceFile:256)
[18:46:15 WARN]:        at net.minecraft.server.v1_8_R3.ChunkProviderServer.getChunkAt(SourceFile:335)
[18:46:15 WARN]:        at net.minecraft.server.v1_8_R3.ChunkProviderServer.getChunkAt(SourceFile:330)
[18:46:15 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.getChunkAt(SourceFile:233)
[18:46:15 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.getBlockAt(SourceFile:182)
[18:46:15 WARN]:        at me.frep.vulcan.spigot.Vulcan_mT.Vulcan_n(Vulcan_mT.java:35)
[18:46:15 WARN]:        at me.frep.vulcan.spigot.Vulcan_Mo.Vulcan_bg(Vulcan_Mo.java:341)
[18:46:15 WARN]:        at me.frep.vulcan.spigot.Vulcan_Mo.Vulcan_yD(Vulcan_Mo.java:166)
[18:46:15 WARN]:        at me.frep.vulcan.spigot.Vulcan_mP.Vulcan_v(Vulcan_mP.java:41)
[18:46:15 WARN]:        at me.frep.vulcan.spigot.Vulcan_MA.lambda$onPacketPlayReceive$0(Vulcan_MA.java:44)
[18:46:15 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[18:46:15 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[18:46:15 WARN]:        at java.lang.Thread.run(Thread.java:748)
[18:46:15 WARN]: Caused by: java.lang.InterruptedException
[18:46:15 WARN]:        at java.util.concurrent.FutureTask.awaitDone(FutureTask.java:404)
[18:46:15 WARN]:        at java.util.concurrent.FutureTask.get(FutureTask.java:191)
[18:46:15 WARN]:        at net.minecraft.server.v1_8_R3.ImanityAsyncChunkProvider.getChunkAt(SourceFile:254)
[18:46:15 WARN]:        ... 12 more

```

### Plugin list

only my own hub plugin.

### Steps/models to reproduce (if known)

generate chunks and just /stop

### ImanitySpigot3 version

[18:45:17 INFO]: This Server is currently running ImanitySpigot3 Premium
[18:45:17 INFO]: Version: 2021.10.1 BUILD 2

### Agreements

- [X] I am running the latest version of ImanitySpigot3 available from
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have compared the issue inbetween TacoSpigot 1.8.8 and ImanitySpigot3 And only ImanitySpigot3 occured this issue.

### Other

nothing

**Comment by LeeGodSRC** [comment]
Only your own hub plugin? why your stacktrace says you have vulcan?
