### ISSUE TITLE
Netty bug (Frost Tablist)

### ISSUE THREAD

**Issue by PenguThePenguin** [Imanity-Software/ImanitySpigot3-git#51]
### Stack trace

[19:37:46] [ERROR]: [Frost] Cannot inject incomming channel [id: 0xff2fcb49, L:/127.0.0.1:25567 - R:/127.0.0.1:37762]
java.util.NoSuchElementException: packet_handler
	at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1073) ~[netty-4.1.60.Final.jar:4.1.60.Final]
	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:248) ~[netty-4.1.60.Final.jar:4.1.60.Final]
	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:237) ~[netty-4.1.60.Final.jar:4.1.60.Final]
	at club.frozed.tablist.util.TinyProtocol_v1_8.injectChannelInternal(TinyProtocol_v1_8.java:369) ~[?:?]
	at club.frozed.tablist.util.TinyProtocol_v1_8.access$300(TinyProtocol_v1_8.java:44) ~[?:?]
	at club.frozed.tablist.util.TinyProtocol_v1_8$2.initChannel(TinyProtocol_v1_8.java:133) ~[?:?]
	at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129) ~[netty-4.1.60.Final.jar:4.1.60.Final]
	at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112) ~[netty-4.1.60.Final.jar:4.1.60.Final]
	at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:938) ~[netty-4.1.60.Final.jar:4.1.60.Final]
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:609) ~[netty-4.1.60.Final.jar:4.1.60.Final]
	at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:223) ~[netty-4.1.60.Final.jar:4.1.60.Final]
	at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:381) ~[netty-4.1.60.Final.jar:4.1.60.Final]
	at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:370) ~[netty-4.1.60.Final.jar:4.1.60.Final]
	at club.frozed.tablist.util.TinyProtocol_v1_8$3.initChannel(TinyProtocol_v1_8.java:148) ~[?:?]
	at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129) ~[netty-4.1.60.Final.jar:4.1.60.Final]
	at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112) ~[netty-4.1.60.Final.jar:4.1.60.Final]
	at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:938) ~[netty-4.1.60.Final.jar:4.1.60.Final]
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:609) ~[netty-4.1.60.Final.jar:4.1.60.Final]
	at io.netty.channel.DefaultChannelPipeline.access$100(DefaultChannelPipeline.java:46) ~[netty-4.1.60.Final.jar:4.1.60.Final]
	at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1463) ~[netty-4.1.60.Final.jar:4.1.60.Final]
	at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1115) ~[netty-4.1.60.Final.jar:4.1.60.Final]
	at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:650) ~[netty-4.1.60.Final.jar:4.1.60.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:502) ~[netty-4.1.60.Final.jar:4.1.60.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:417) ~[netty-4.1.60.Final.jar:4.1.60.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:474) ~[netty-4.1.60.Final.jar:4.1.60.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[netty-4.1.60.Final.jar:4.1.60.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[netty-4.1.60.Final.jar:4.1.60.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384) ~[netty-4.1.60.Final.jar:4.1.60.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-4.1.60.Final.jar:4.1.60.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-4.1.60.Final.jar:4.1.60.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]

### Plugin list

> pl
[19:46:12 INFO]: Plugins (8): FastAsyncWorldEdit (19.11.13-5505943-1282-22.3.5), KnockbackController (1.0), Crux (3.0), spark (1.4.3), ViaVersion (4.0.1), ProtocolLib (4.5.1), ViaRewind (2.0.1), WorldEdit (6.1.7;dd00bb1)

### ImanitySpigot3 version

2021.10.1 BUILD 8

### Agreements

- [X] I am running the latest version of ImanitySpigot3 available from
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [x] I have compared the issue inbetween TacoSpigot 1.8.8 and ImanitySpigot3 And only ImanitySpigot3 occured this issue.

**Comment by LeeGodSRC** [comment]
Hello, The issue is known and we've tried contacting frost developers for a fix
The fix requires plugin side to work on due to we updated netty to latest version possible
But frost developer has not give any further response about the fix we requested
![image](https://user-images.githubusercontent.com/36093806/139544644-cc412852-bbbd-41bb-b293-2cbb1210d1f8.png)
