### ISSUE TITLE
[BUG] NullPointerException on /plugins

### ISSUE THREAD

**Issue by LeeGodSRC** [Imanity-Software/ImanitySpigot3-git#6]
**Expected behavior**
Correctly showing information about plugins on command execution

**Observed/Actual behavior**
NullPointerException on command execution

**Steps/models to reproduce**
Execute /plugins in the server

**Plugin list**
- ProtocolLib

**ImanitySpigot3 version**
2021.06.2 BUILD 2

**Please agree to the following.  (fill x in the [ ])**
- [x] I am running the latest version of ImanitySpigot3 available from #client-info channel in our discord.
- [x] I have searched for and ensured there isn't already an open issue regarding this.
- [x] I have compared the issue inbetween TacoSpigot 1.8.8 and ImanitySpigot3 And only ImanitySpigot3 occured this issue.

**Additional context**
Stacktrace:
```
[21:40:58 WARN]: [Server thread] Unexpected exception while parsing console command "pl"
org.bukkit.command.CommandException: Unhandled exception executing 'pl' in org.bukkit.command.defaults.PluginsCommand(plugins)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:150) ~[spigot.jar:git-iSpigot-PaperEdition]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(SourceFile:679) ~[spigot.jar:git-iSpigot-PaperEdition]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(SourceFile:642) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.DedicatedServer.aO(SourceFile:491) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(SourceFile:451) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(SourceFile:835) ~[spigot.jar:git-iSpigot-PaperEdition]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(SourceFile:737) ~[spigot.jar:git-iSpigot-PaperEdition]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.NullPointerException
        at java.lang.String.replace(String.java:2240) ~[?:1.8.0_292]
        at org.bukkit.command.defaults.PluginsCommand.getPluginList(PluginsCommand.java:59) ~[spigot.jar:git-iSpigot-PaperEdition]
        at org.bukkit.command.defaults.PluginsCommand.execute(PluginsCommand.java:25) ~[spigot.jar:git-iSpigot-PaperEdition]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:143) ~[spigot.jar:git-iSpigot-PaperEdition]
        ... 7 more
```

**Comment by LeeGodSRC** [comment]
will be fixed in 2021.06.2 BUILD 3
