### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by LudnicaKiller** [Imanity-Software/ImanitySpigot3-git#63]
### Stack trace

https://paste.imanity.dev/PF6soI5

### Plugin list

https://prnt.sc/20dxn4p

### Steps/models to reproduce (if known)

On startup

### ImanitySpigot3 version

2021.11.1 LTS BUILD 2

### Agreements

- [X] I am running the latest version of ImanitySpigot3 available from
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have compared the issue inbetween TacoSpigot 1.8.8 and ImanitySpigot3 And only ImanitySpigot3 occured this issue.

**Comment by LeeGodSRC** [comment]
Hello, can you provide the full log from start to crash?

**Comment by LudnicaKiller** [comment]
@LeeGodSRC I can in private

**Comment by LeeGodSRC** [comment]
```java
[18:54:13] [WARN]: Exception in thread "Craft Scheduler Thread - 16" org.apache.commons.lang.UnhandledException: Plugin Essentials v2.15.0.16 generated an exception while executing task 62
[18:54:13] [WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(SourceFile:57)
[18:54:13] [WARN]: 	at org.github.paperspigot.ServerSchedulerReportingWrapper.run(SourceFile:22)
[18:54:13] [WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[18:54:13] [WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[18:54:13] [WARN]: 	at java.lang.Thread.run(Thread.java:748)
[18:54:13] [WARN]: Caused by: java.lang.NoSuchMethodError: com.earth2me.essentials.storage.BukkitConstructor.constructScalar(Lorg/yaml/snakeyaml/nodes/ScalarNode;)Ljava/lang/Object;
[18:54:13] [WARN]: 	at com.earth2me.essentials.storage.BukkitConstructor.access$200(BukkitConstructor.java:21)
[18:54:13] [WARN]: 	at com.earth2me.essentials.storage.BukkitConstructor$ConstructBukkitMapping.construct(BukkitConstructor.java:206)
[18:54:13] [WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:216)
[18:54:13] [WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:205)
[18:54:13] [WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:465)
[18:54:13] [WARN]: 	at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:184)
[18:54:13] [WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:446)
[18:54:13] [WARN]: 	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:136)
[18:54:13] [WARN]: 	at com.earth2me.essentials.storage.BukkitConstructor$ConstructBukkitMapping.construct(BukkitConstructor.java:236)
[18:54:13] [WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:216)
[18:54:13] [WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:205)
[18:54:13] [WARN]: 	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.newInstance(Constructor.java:283)
[18:54:13] [WARN]: 	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:246)
[18:54:13] [WARN]: 	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:149)
[18:54:13] [WARN]: 	at com.earth2me.essentials.storage.BukkitConstructor$ConstructBukkitMapping.construct(BukkitConstructor.java:236)
[18:54:13] [WARN]: 	at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:309)
[18:54:13] [WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:216)
[18:54:13] [WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:205)
[18:54:13] [WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:164)
[18:54:13] [WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:148)
[18:54:13] [WARN]: 	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:525)
[18:54:13] [WARN]: 	at org.yaml.snakeyaml.Yaml.load(Yaml.java:468)
[18:54:13] [WARN]: 	at com.earth2me.essentials.storage.YamlStorageReader.load(YamlStorageReader.java:41)
[18:54:13] [WARN]: 	at com.earth2me.essentials.storage.AbstractDelayedYamlFileReader.run(AbstractDelayedYamlFileReader.java:33)
[18:54:13] [WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(SourceFile:59)
[18:54:13] [WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(SourceFile:53)
[18:54:13] [WARN]: 	... 4 more
```

This error appears before the crash and it has potential to be the cause of the crash
Are you sure your essentials core and spawns version matches? can you try to download latest version of both?

**Comment by LudnicaKiller** [comment]
Yes, they are the same version https://prnt.sc/20fownd

**Comment by LeeGodSRC** [comment]
Can you try latest version of essentials?

**Comment by LudnicaKiller** [comment]
I will try it now

**Comment by Whizyyy** [comment]
6 days without response, if there is no answer in the next 24h this issue will be considered as fixed. Also please try with the latest version: 2021.11.1 LTS BUILD 5 which contains some bug fixes
