### ISSUE TITLE
Location.getChunk() on unloaded chunk make the server crash

### ISSUE THREAD

**Issue by NivixX** [Imanity-Software/ImanitySpigot3-git#70]
### Stack trace

[09:12:49] [ERROR]: Encountered an unexpected exception
net.minecraft.server.v1_8_R3.ReportedException: Exception ticking world
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(SourceFile:1008) ~[spigot.jar:git-iSpigot-PaperEdition]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(SourceFile:502) ~[spigot.jar:git-iSpigot-PaperEdition]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(SourceFile:868) ~[spigot.jar:git-iSpigot-PaperEdition]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(SourceFile:769) ~[spigot.jar:git-iSpigot-PaperEdition]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 499
	at it.unimi.dsi.fastutil.longs.LongOpenHashSet$SetIterator.nextLong(LongOpenHashSet.java:466) ~[fastutil-8.2.2.jar:?]
	at org.bukkit.craftbukkit.v1_8_R3.util.AsyncCatchLongSet$1.nextLong(SourceFile:44) ~[spigot.jar:git-iSpigot-PaperEdition]
	at net.minecraft.server.v1_8_R3.ChunkProviderServer.unloadChunks(SourceFile:741) ~[spigot.jar:git-iSpigot-PaperEdition]
	at net.minecraft.server.v1_8_R3.WorldServer.doTick(SourceFile:309) ~[spigot.jar:git-iSpigot-PaperEdition]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(SourceFile:997) ~[spigot.jar:git-iSpigot-PaperEdition]
	... 4 more
[09:12:49] [ERROR]: 	Cause of unexpected exception was
java.lang.ArrayIndexOutOfBoundsException: 499
	at it.unimi.dsi.fastutil.longs.LongOpenHashSet$SetIterator.nextLong(LongOpenHashSet.java:466) ~[fastutil-8.2.2.jar:?]
	at org.bukkit.craftbukkit.v1_8_R3.util.AsyncCatchLongSet$1.nextLong(SourceFile:44) ~[spigot.jar:git-iSpigot-PaperEdition]
	at net.minecraft.server.v1_8_R3.ChunkProviderServer.unloadChunks(SourceFile:741) ~[spigot.jar:git-iSpigot-PaperEdition]
	at net.minecraft.server.v1_8_R3.WorldServer.doTick(SourceFile:309) ~[spigot.jar:git-iSpigot-PaperEdition]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(SourceFile:997) ~[spigot.jar:git-iSpigot-PaperEdition]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(SourceFile:502) ~[spigot.jar:git-iSpigot-PaperEdition]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(SourceFile:868) ~[spigot.jar:git-iSpigot-PaperEdition]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(SourceFile:769) ~[spigot.jar:git-iSpigot-PaperEdition]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
[09:12:49] [INFO]: Stopping server

### Plugin list

custom

### Steps/models to reproduce (if known)

call Location.getChunk() on an unloaded chunk
(or just unloaded chunk, eg: within ChunkUnloadEvent)

In my usecase, I have a list of cached location where I don't want the chunk being unloaded, so I'm just listening to the event and cancel the event if any of the location.getChunk() match with the one from the event.
note : given this bug, is it actually possible to cancel the unload of a chunk ?

### ImanitySpigot3 version

2021.11.1 LTS BUILD 5

### Agreements

- [X] I am running the latest version of ImanitySpigot3 available from
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have compared the issue inbetween TacoSpigot 1.8.8 and ImanitySpigot3 And only ImanitySpigot3 occured this issue.

**Comment by LeeGodSRC** [comment]
Fixed in **2021.12.1 BUILD 2**
